import { buildTopics } from "./buildTopics";

export const funTopics = buildTopics("fun", [
  "Does pineapple belong on pizza?",
  "Is water wet?",
  "Is a hot dog a sandwich?",
  "Is cereal a soup?",
  "Should fries be dipped in milkshakes?",
  "Is breakfast for dinner underrated?",
  "Should pizza be eaten with a fork and knife?",
  "Are crunchy chips better than fluffy chips?",
  "Should ketchup live in the fridge?",
  "Is tea better than coffee?",
  "Should biscuits be dunked until they nearly collapse?",
  "Is sparkling water just angry water?",
  "Should dessert be served before dinner?",
  "Is soup a drink or a meal?",
  "Should the end slice of bread be respected?",
  "Is the middle brownie piece better than the corner?",
  "Should crisp sandwiches be considered fine dining?",
  "Is plain pasta acceptable as a full meal?",
  "Should every meal include a sauce?",
  "Are leftovers better the next day?",
  "Should socks match?",
  "Are hoodies the greatest clothing invention?",
  "Should pyjamas be allowed in public?",
  "Is formal wear overrated?",
  "Should sunglasses be worn indoors for confidence?",
  "Are pockets a human right?",
  "Should hats be allowed at every occasion?",
  "Are trainers better than every other shoe?",
  "Should people dress for comfort over style?",
  "Is wearing all black always a good idea?",
  "Should alarms have a snooze button?",
  "Is making the bed worth it?",
  "Should weekends be three days long?",
  "Is being five minutes late acceptable?",
  "Should calendars include nap appointments?",
  "Are morning people more productive?",
  "Is night-time creativity better than morning focus?",
  "Should elevator small talk be banned?",
  "Is queueing a sport?",
  "Should everyone have a personal theme song?",
  "Are movie trailers too revealing?",
  "Should spoilers expire after one year?",
  "Is the book usually better than the film?",
  "Should villains get more screen time?",
  "Are sequels usually necessary?",
  "Should every song be shorter than three minutes?",
  "Is live music better than perfect recordings?",
  "Should playlists replace albums?",
  "Are subtitles always better?",
  "Should reality TV be respected as strategy?",
  "Is board game night better than movie night?",
  "Should video games count as sport?",
  "Are puzzles better than quizzes?",
  "Should every party have a strict playlist captain?",
  "Is karaoke bravery or chaos?",
  "Should dancing be mandatory at weddings?",
  "Are surprise parties a good idea?",
  "Should birthday weeks replace birthdays?",
  "Is clapping when a plane lands acceptable?",
  "Should window seats outrank aisle seats?",
  "Is packing early a sign of wisdom?",
  "Should holidays have no schedules?",
  "Are staycations underrated?",
  "Should maps be trusted over vibes?",
  "Is getting lost part of the adventure?",
  "Should souvenir shops be judged as museums?",
  "Are airport snacks unfairly expensive?",
  "Should suitcases have built-in seats?",
  "Is inbox zero a myth?",
  "Should group chats have elected leaders?",
  "Are voice notes better than texts?",
  "Should read receipts be banned?",
  "Is autocorrect secretly useful?",
  "Should phone batteries last a full week?",
  "Are smart watches too demanding?",
  "Should every app have dark mode?",
  "Is typing in all caps ever acceptable?",
  "Should emojis count as punctuation?",
  "Is neat handwriting a superpower?",
  "Should everyone learn one magic trick?",
  "Are riddles better than jokes?",
  "Should compliments be more specific?",
  "Is confidence mostly performance?",
  "Should speeches always begin with a question?",
  "Are dramatic pauses powerful or awkward?",
  "Should hand gestures be planned?",
  "Is eye contact overrated?",
  "Should every argument include one joke?",
  "Is enthusiasm more persuasive than evidence?",
  "Should debates have walk-on music?",
  "Are trophies better than certificates?",
  "Should there be a world championship for everyday chores?",
  "Is folding fitted sheets impossible by design?",
  "Should remote controls have a find-me button?",
  "Are fridge magnets an underrated art form?",
  "Should every room have a snack drawer?",
  "Is a perfectly packed dishwasher a life skill?",
  "Should umbrellas be redesigned from scratch?",
  "Are rainy days better for productivity?",
  "Should names for Wi-Fi networks be judged publicly?",
]);
