import { buildTopics } from "./buildTopics";

export const generalTopics = buildTopics("general", [
  "Should social media be regulated?",
  "Is capitalism the best economic system?",
  "Should gun ownership be more restricted?",
  "Is immigration good for society?",
  "Should euthanasia be legal?",
  "Should abortion be legal?",
  "Should governments tax extreme wealth more heavily?",
  "Should AI-generated content be labelled by law?",
  "Should voting be compulsory?",
  "Should the death penalty ever be allowed?",
  "Should free speech include offensive opinions?",
  "Should private schools be abolished?",
  "Should university education be free?",
  "Should healthcare be free at the point of use?",
  "Should climate protestors who block roads face harsher penalties?",
  "Should nuclear power be expanded?",
  "Should meat consumption be taxed?",
  "Should social media companies verify every user?",
  "Should children be banned from smartphones before 14?",
  "Should facial recognition be used by police?",
  "Should remote work become the default?",
  "Should billionaires exist?",
  "Should governments introduce universal basic income?",
  "Should unpaid internships be illegal?",
  "Should companies be required to publish salary ranges?",
  "Should four-day workweeks become standard?",
  "Should prisons focus more on rehabilitation than punishment?",
  "Should drug possession be decriminalized?",
  "Should athletes be allowed to protest during national anthems?",
  "Should trans athletes compete in categories matching gender identity?",
  "Should hate speech laws be stronger?",
  "Should religion have a role in public schools?",
  "Should animal testing for medicine continue?",
  "Should zoos still exist?",
  "Should space exploration be a public priority?",
  "Should governments control rent prices?",
  "Should cryptocurrency be tightly regulated?",
  "Should cash remain legally protected?",
  "Should governments ban addictive app design?",
  "Should children's data be protected by stricter laws?",
  "Should AI replace human judges for minor legal decisions?",
  "Should driverless cars be allowed on public roads?",
  "Should governments subsidize electric cars?",
  "Should cities ban private cars from central areas?",
  "Should public transport be free?",
  "Should fast fashion be taxed?",
  "Should schools teach financial literacy before algebra?",
  "Should exams be replaced by continuous assessment?",
  "Should the voting age be lowered to 16?",
  "Should politicians have term limits?",
  "Should lobbying be more restricted?",
  "Should news organizations receive public funding?",
  "Should misinformation be illegal?",
  "Should governments negotiate with terrorist groups?",
  "Should military conscription ever return?",
  "Should countries be required to accept climate refugees?",
  "Should international courts have more power?",
  "Should rich countries pay climate reparations?",
  "Should large tech companies be broken up?",
  "Should online anonymity be protected?",
  "Should parents be fined for children's online bullying?",
  "Should violent video games be restricted for minors?",
  "Should influencers be licensed when giving health advice?",
  "Should junk food advertising to children be banned?",
  "Should sugar taxes be expanded?",
  "Should alcohol sponsorship of sport be banned?",
  "Should gambling ads be banned?",
  "Should surrogacy be legal in all countries?",
  "Should genetic editing of embryos be allowed?",
  "Should organ donation be opt-out by default?",
  "Should vaccine mandates be used in public health emergencies?",
  "Should pandemic lockdowns be used again if needed?",
  "Should body cameras be mandatory for police?",
  "Should juries decide complex fraud cases?",
  "Should governments use prison labor?",
  "Should statues of controversial historical figures be removed?",
  "Should museums return artefacts taken during colonialism?",
  "Should national borders matter less in a globalized world?",
  "Should population decline be treated as a crisis?",
  "Should having children be encouraged by government incentives?",
  "Should marriage laws give more support to caregivers?",
  "Should divorce be made easier?",
  "Should celebrity culture be taken seriously as social influence?",
  "Should cancel culture be seen as accountability?",
  "Should art be separated from the artist?",
  "Should governments fund the arts during economic crises?",
  "Should sports teams owned by states face restrictions?",
  "Should hosting major sporting events be worth the cost?",
  "Should men and women athletes receive equal prize money?",
  "Should performance-enhancing drugs be legalized in sport?",
  "Should schools use AI tutors?",
  "Should workplaces monitor employee productivity software?",
  "Should data centers face energy limits?",
  "Should water be treated as a human right?",
  "Should private companies own essential infrastructure?",
  "Should homeless encampments be cleared from public spaces?",
  "Should protests require permits?",
  "Should whistleblowers be given stronger protections?",
  "Should governments ban political deepfakes?",
  "Should democracy limit campaign spending?",
]);
