import { buildTopics } from "./buildTopics";

export const irishTopics = buildTopics("irish", [
  "Should Irish remain compulsory in schools?",
  "Is Ireland doing enough to solve the housing crisis?",
  "Should Dublin MetroLink be fast-tracked even if costs rise?",
  "Is rural Ireland being neglected?",
  "Should Ireland remain militarily neutral?",
  "Should the voting age be lowered in Ireland?",
  "Is the Leaving Cert a fair system?",
  "Should public transport be free in Ireland?",
  "Should Ireland plan seriously for a united Ireland?",
  "Should the GAA receive more public funding than other sports?",
  "Should vacant state buildings be converted into homes?",
  "Should Ireland tax vacant homes more aggressively?",
  "Should rent pressure zones be made stricter?",
  "Should institutional investors be limited in Irish housing?",
  "Should higher-density apartments be prioritized in Dublin?",
  "Should planning objections be limited for critical infrastructure?",
  "Is MetroLink worth waiting until the 2030s?",
  "Should BusConnects prioritize buses over parking?",
  "Should Cork get a Luas before more motorway spending?",
  "Should the Galway Ring Road go ahead?",
  "Should Ireland build offshore wind farms faster?",
  "Should data centers face stricter electricity limits in Ireland?",
  "Should farmers receive more support for climate targets?",
  "Should turf-cutting restrictions be tightened?",
  "Should Ireland invest more in flood defences?",
  "Should Uisce Eireann have more power over housing delivery?",
  "Should school phone restrictions become national law?",
  "Should Leaving Cert reform include major project work?",
  "Should Irish schools teach climate action as a core subject?",
  "Should Transition Year be mandatory?",
  "Should school transport be free in rural Ireland?",
  "Should Gaeltacht communities get stronger housing protections?",
  "Should more public services be available through Irish?",
  "Should the Gaeltacht get priority broadband and remote work hubs?",
  "Should RTE receive more stable public funding?",
  "Should the TV licence be replaced by general taxation?",
  "Should Irish media receive support against misinformation?",
  "Should Ireland ban gambling ads during sports broadcasts?",
  "Should alcohol sponsorship in Irish sport be capped?",
  "Should inter-county GAA players receive payment?",
  "Should Casement Park receive Irish state funding?",
  "Should the League of Ireland receive major public investment?",
  "Should Ireland bid for more major sporting events?",
  "Should Dublin Airport expand passenger capacity?",
  "Should Shannon and Cork airports receive more route support?",
  "Should Ireland introduce tourist taxes in busy cities?",
  "Should short-term lets be restricted in housing pressure zones?",
  "Should Dublin city centre become more car-free?",
  "Should cycling infrastructure take road space from cars?",
  "Should rural bus services be guaranteed by law?",
  "Should Irish rail reopen more regional lines?",
  "Should the Western Rail Corridor be completed?",
  "Should Ireland prioritize rail freight over road freight?",
  "Should Rosslare and other ports be expanded for offshore energy?",
  "Should Ireland increase defence spending?",
  "Should Ireland join more EU defence projects?",
  "Should Ireland make Palestine a central foreign policy priority?",
  "Should Ireland change its corporation tax model?",
  "Do multinationals have too much influence over Ireland?",
  "Should Ireland build a larger sovereign wealth fund?",
  "Should minimum wage rises be faster in Ireland?",
  "Should childcare be treated as public infrastructure?",
  "Should parental leave be expanded further?",
  "Should Ireland trial a four-day public sector workweek?",
  "Should public sector pay deals prioritize lower-paid workers?",
  "Should Ireland do more to attract teachers and nurses home?",
  "Should immigration increase to fill labour shortages?",
  "Should asylum accommodation be spread more evenly across Ireland?",
  "Should Ireland replace direct provision completely?",
  "Should communities have more say in refugee accommodation?",
  "Should hate crime laws be strengthened in Ireland?",
  "Should policing in Dublin city centre become more visible?",
  "Should sentencing for repeat offenders be tougher in Ireland?",
  "Should Ireland decriminalize drug possession for personal use?",
  "Should supervised injection facilities be expanded?",
  "Should cannabis be legalized in Ireland?",
  "Should assisted dying be legal in Ireland?",
  "Should Ireland lower the voting age to 16 for local elections?",
  "Should Seanad reform be prioritized?",
  "Should directly elected mayors be introduced beyond Limerick?",
  "Should Dublin have a stronger metropolitan authority?",
  "Should county councils get more tax-raising powers?",
  "Should Ireland introduce water charges for high use?",
  "Should waste collection return to public control?",
  "Should the bottle return scheme be expanded?",
  "Should single-use vapes be banned in Ireland?",
  "Should Irish peatlands be restored faster?",
  "Should forestry policy prioritize native trees over commercial spruce?",
  "Should Ireland protect more marine areas from fishing?",
  "Should coastal towns restrict holiday homes?",
  "Should rural pubs receive cultural support?",
  "Should small towns get more remote-work investment?",
  "Should Ireland build more student accommodation on public land?",
  "Should universities reduce reliance on international fees?",
  "Should apprenticeships be valued equally with degrees?",
  "Should CAO points dominate college entry?",
  "Should Irish history teaching focus more on contemporary Ireland?",
  "Should Northern Ireland be taught more widely in schools?",
  "Should Ireland create a national AI strategy for schools and work?",
  "Should Ireland preserve neutrality in cyber conflicts?",
]);
