import { buildTopics } from "./buildTopics";

export const schoolTopics = buildTopics("school", [
  "Should school uniforms be required?",
  "Should homework be banned?",
  "Should phones be allowed in school?",
  "Should school start later?",
  "Should exams be replaced by projects?",
  "Should students have longer lunch breaks?",
  "Should PE be compulsory?",
  "Should class sizes be smaller?",
  "Should schools try a four-day week?",
  "Should grades be abolished?",
  "Should students choose subjects earlier?",
  "Should financial literacy be mandatory?",
  "Should cooking be taught in every school?",
  "Should coding be mandatory?",
  "Should public speaking be mandatory?",
  "Should every school have a debate club?",
  "Should school trips count as learning time?",
  "Should students learn outdoors more often?",
  "Should schools spend more time on art and music?",
  "Should every school day include reading time?",
  "Should school libraries receive more funding?",
  "Should lockers be available to every student?",
  "Should school cafeterias serve only healthy food?",
  "Should vending machines be removed from schools?",
  "Should water fountains be required in schools?",
  "Should students help design the school uniform?",
  "Should casual clothes days happen every week?",
  "Should teachers assign seats?",
  "Should group work happen more often?",
  "Should weekend homework be banned?",
  "Should summer holidays be shorter with more breaks during the year?",
  "Should the school year start later after summer?",
  "Should schools give awards for attendance?",
  "Can perfect attendance put too much pressure on students?",
  "Should student councils have more real power?",
  "Should students vote on some school rules?",
  "Should kindness classes be part of school?",
  "Should mindfulness be taught in school?",
  "Is competition good for students?",
  "Should effort prizes matter more than grade prizes?",
  "Should AI tools be allowed for homework?",
  "Should calculators be introduced earlier?",
  "Should tablets replace textbooks?",
  "Is handwriting still important?",
  "Are spelling tests still useful?",
  "Does memorization still matter?",
  "Should oral presentations be graded?",
  "Should drama be compulsory?",
  "Should music lessons be free for every student?",
  "Should all sports teams get equal funding?",
  "Should schools have esports clubs?",
  "Should every school have a chess club?",
  "Should students run a school newspaper?",
  "Should schools give rewards for recycling?",
  "Should uniforms be made cheaper by law?",
  "Should school buses be free?",
  "Should schools support bike-to-school programmes?",
  "Should road safety be taught every year?",
  "Should first aid be mandatory in school?",
  "Should swimming lessons be part of school?",
  "Are life skills more important than test scores?",
  "Should entrepreneurship be taught in school?",
  "Should work experience be mandatory?",
  "Should Transition Year be mandatory?",
  "Should older students mentor younger students?",
  "Should students tutor each other more often?",
  "Should parents see grades instantly online?",
  "Should parent-teacher meetings happen online?",
  "Are school rules too strict?",
  "Is detention a useful punishment?",
  "Are reward systems fair to all students?",
  "Should students evaluate teachers?",
  "Should schools plan better for substitute classes?",
  "Should every school have a garden?",
  "Do uniforms improve focus?",
  "Should students learn another language earlier?",
  "Should Irish language lessons be more practical and fun?",
  "Should classic books stay on reading lists?",
  "Should graphic novels count as literature?",
  "Should podcasts count as homework?",
  "Should educational YouTube be used in class?",
  "Should every school have strong Wi-Fi?",
  "Should cyberbullying lessons happen every year?",
  "Should schools have a screen-free day each month?",
  "Should schools run more festivals and showcases?",
  "Should every school have a talent show?",
  "Should school sport focus more on participation than winning?",
  "Should every student receive a participation medal?",
  "Should school assemblies happen every week?",
  "Should students teach short lessons sometimes?",
  "Should open-book tests be used more often?",
  "Should grades wait until secondary school?",
  "Should schools do more to help students move from primary to secondary?",
  "Should classes be shorter?",
  "Should double classes be avoided?",
  "Should students get a short break between every class?",
  "Should every school have quiet study rooms?",
  "Should school counselling be available to every student?",
  "Should sleep education be taught in school?",
  "Should every school have a student suggestion box?",
]);
